language: python

cache: pip

os:
  - osx
  - linux
  
python:
  - 3.7
  - 3.8

before_install:
  # Strangely enough numpy is already installed on Travis's VMs
  - pip install -r requirements.txt.dev

install:
  - pip install -e .

script:
  - pytest -xvv tests
  - safety check
